### ISSUE TITLE
Application download progress issues

### ISSUE THREAD

**Issue by floion** [balena-io-modules/docker-progress#7]
There seems to be an issue with the app download progress reporting.

There is the progress bar showing progress from 0 to 100%; then it fills up as expected and disappears and the label changes to only "Downloading" and it still stays there for a while (ranging from 3 minutes up to 10 minutes, depending on the board, in which time no progress or any other information is presented to the user about the current status of the operation being performed).

**Comment by floion** [comment]
@abresas

**Comment by petrosagg** [comment]
After some investigation this turned out to be the extracting phase, and in the case of fast internet it might take longer than the download itself. We discussed with Shaun that the device should enter an "Applying" state after the download that has its own progress bar.

Another idea would be to merge the two processes into a single progress bar that will include both the download and the extraction phase. Thoughts @shaunmulligan ?

**Comment by shaunmulligan** [comment]
@petrosagg I think either solution would be miles better than we have now. We could have one progress bar, but the state label changes from "Downloading" --> "Applying" for the last 50% or whatever. it might be kinda weird, but I think its good for people to get an idea of which parts of the process are taking the most time for them.

**Comment by petrosagg** [comment]
If we go for state label change then we'll be restarting the progress bar from zero

**Comment by shaunmulligan** [comment]
I think I would prefer a split with 2 progress bars, and on the UI we can make them visually different. I think its important for users to appreciate that time is being spent extracting, etc.

**Comment by shaunmulligan** [comment]
@dfunckt so the supervisor component of this is kinda done now right? so we need some UI design and implementation right?

**Comment by dfunckt** [comment]
@shaunmulligan, needs a tiny bit of work in the supervisor to take advantage of the newly exposed extraction progress, cc @pcarranzav
